#!/usr/bin/env python3
"""Generates Packages/DeathRaceKit/Sources/VTCore/Unicode/UnicodeTables.swift from the
Unicode Character Database.

Usage: scripts/gen-unicode-tables.py [--version 18.0.0] [--cache DIR]

The output records the UCD version and the SHA-256 of every input file, so a review can
confirm exactly what the tables were built from. Width rules (what a terminal cell grid
needs, following the de-facto wcwidth behaviour Ghostty, kitty and foot share):

  width 0: nonspacing and enclosing marks (Mn, Me), format controls (Cf) except U+00AD SOFT
           HYPHEN, Hangul Jamo medial vowels and final consonants (U+1160..U+11FF,
           U+D7B0..U+D7FF), variation selectors, and the zero-width space family.
  width 2: East Asian Width W or F, and anything with Emoji_Presentation=Yes.
  width 1: everything else that is printable.

Grapheme properties emitted for clustering: Extended_Pictographic, Emoji_Modifier,
Regional_Indicator and Grapheme_Extend.
"""

import argparse
import hashlib
import os
import sys
import urllib.request

FILES = {
    "EastAsianWidth.txt": "ucd/EastAsianWidth.txt",
    "DerivedGeneralCategory.txt": "ucd/extracted/DerivedGeneralCategory.txt",
    "emoji-data.txt": "ucd/emoji/emoji-data.txt",
    "DerivedCoreProperties.txt": "ucd/DerivedCoreProperties.txt",
}

OUT = os.path.join(os.path.dirname(__file__), "..", "Packages", "DeathRaceKit", "Sources",
                   "VTCore", "Unicode", "UnicodeTables.swift")


def fetch(version, cache):
    os.makedirs(cache, exist_ok=True)
    texts, digests = {}, {}
    for name, path in FILES.items():
        local = os.path.join(cache, f"{version}-{name}")
        if not os.path.exists(local):
            url = f"https://www.unicode.org/Public/{version}/{path}"
            print(f"downloading {url}", file=sys.stderr)
            with urllib.request.urlopen(url) as response, open(local, "wb") as out:
                out.write(response.read())
        data = open(local, "rb").read()
        digests[name] = hashlib.sha256(data).hexdigest()
        texts[name] = data.decode("utf-8")
    return texts, digests


def parse(text):
    """Yields (start, end, fields) for each data line."""
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        cols = [c.strip() for c in line.split(";")]
        span = cols[0]
        if ".." in span:
            a, b = span.split("..")
            start, end = int(a, 16), int(b, 16)
        else:
            start = end = int(span, 16)
        yield start, end, cols[1:]


def collect(text, predicate):
    out = set()
    for start, end, fields in parse(text):
        if predicate(fields):
            out.update(range(start, end + 1))
    return out


def ranges(points):
    """Merges a set of code points into sorted inclusive ranges."""
    out = []
    for cp in sorted(points):
        if out and cp == out[-1][1] + 1:
            out[-1][1] = cp
        else:
            out.append([cp, cp])
    return out


def swift_ranges(name, points, doc):
    rs = ranges(points)
    lines = [f"    /// {doc} ({len(rs)} ranges)", f"    static let {name}: [ClosedRange<UInt32>] = ["]
    row = []
    for a, b in rs:
        row.append(f"0x{a:X}...0x{b:X}")
        if len(row) == 6:
            lines.append("        " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("        " + ", ".join(row) + ",")
    lines.append("    ]")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", default="18.0.0")
    ap.add_argument("--cache", default=os.path.join(os.path.dirname(__file__), "..", ".build", "ucd"))
    args = ap.parse_args()
    texts, digests = fetch(args.version, args.cache)

    gc = texts["DerivedGeneralCategory.txt"]
    marks = collect(gc, lambda f: f[0] in ("Mn", "Me"))
    formats = collect(gc, lambda f: f[0] == "Cf") - {0x00AD}
    hangul_trailing = set(range(0x1160, 0x1200)) | set(range(0xD7B0, 0xD800))
    zero_width_space = {0x200B}
    zero = marks | formats | hangul_trailing | zero_width_space

    eaw = texts["EastAsianWidth.txt"]
    east_asian_wide = collect(eaw, lambda f: f[0] in ("W", "F"))
    emoji = texts["emoji-data.txt"]
    emoji_presentation = collect(emoji, lambda f: f[0] == "Emoji_Presentation")
    wide = (east_asian_wide | emoji_presentation) - zero

    extended_pictographic = collect(emoji, lambda f: f[0] == "Extended_Pictographic")
    emoji_modifier = collect(emoji, lambda f: f[0] == "Emoji_Modifier")
    grapheme_extend = collect(texts["DerivedCoreProperties.txt"], lambda f: f[0] == "Grapheme_Extend")

    header = [
        f"// Generated by scripts/gen-unicode-tables.py from the Unicode Character Database {args.version}.",
        "// Do not edit by hand; rerun the script. Inputs (SHA-256):",
    ]
    header += [f"//   {name}: {digests[name]}" for name in FILES]
    body = [
        "",
        "// swift-format-ignore-file",
        "",
        "enum UnicodeTables {",
        f'    static let version = "{args.version}"',
        "",
        swift_ranges("zeroWidth", zero, "Width 0: marks, format controls, Hangul trailing jamo, ZWSP"),
        "",
        swift_ranges("doubleWidth", wide, "Width 2: East Asian Wide/Fullwidth and Emoji_Presentation"),
        "",
        swift_ranges("extendedPictographic", extended_pictographic, "Extended_Pictographic"),
        "",
        swift_ranges("emojiModifier", emoji_modifier, "Emoji_Modifier (skin tones)"),
        "",
        swift_ranges("graphemeExtend", grapheme_extend, "Grapheme_Extend"),
        "}",
        "",
    ]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as out:
        out.write("\n".join(header + body))
    print(f"wrote {os.path.relpath(OUT)}: zero={len(ranges(zero))} wide={len(ranges(wide))} "
          f"pictographic={len(ranges(extended_pictographic))} extend={len(ranges(grapheme_extend))} ranges",
          file=sys.stderr)


if __name__ == "__main__":
    main()
